name = "SRaJ"
uuid = "ebfb1966-bb6f-11e9-1d77-c139f3c3d02b"
authors = ["Mateusz Gorski <mateu.gorski@gmail.com>"]
version = "0.1.0"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
julia = "1.1.1"
DataStructures = ">=0.15.0"
